import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Introduction',
      className: "style_album"
    },
    {
      type: 'doc',
      id: 'troubleshooting',
      label: 'Troubleshooting',
      className: "style_start"
    },
    {
      type: "doc",
      id: "placeholders",
      label: "Placeholders",
      className: "style_replace"
    },
    {
      type: 'category',
      id: 'usage',
      label: 'Usage',
      items: [
        {
          type: "autogenerated",
          dirName: 'usage',
        }
      ],
      className: "style_usage"
    },
    {
      type: 'category',
      label: 'Features',
      items: [
        {
          type: "autogenerated",
          dirName: 'features',
        }
      ],
      className: "style_feather"
    },
    {
      type: 'category',
      label: 'Commands',
      items: ['commands/bot'],
      className: "style_command"
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [{
        type: "doc",
        id: "api/index",
        label: "Overview",
        className: "style_booktext"
      }],
      className: "style_route"
    },
    {
      type: 'category',
      label: 'Customization',
      items: [{
        type: "autogenerated",
        dirName: 'customization',
      }],
      className: "style_sparkles"
    },
    {
      type: 'category',
      label: 'Customer',
      items: [{
        type: "doc",
        id: "customer/index",
        label: "Introduction",
        className: "style_booktext"
      }],
      className: "style_settings"
    },
    {
      type: 'category',
      label: 'Changelogs',
      items: [{
        type: 'autogenerated',
        dirName: 'changelogs',
      },],
      className: "style_log"
    },
  ]
};

export default sidebars;
